[package]
name = "canada_sin"
version = "1.0.1"
authors = ["Smitop <smitop2@gmail.com>"]
edition = "2018"
description = "A Rust crate for working with Canadian social insurance numbers"
license = "MIT OR Apache-2.0"

[dependencies]
